name: Qodana Scan

on:
  push:
    branches:
      - master

jobs:
  scan_qodana:
    # only run this action on `vechain/thor` repository
    if: github.repository == 'vechain/thor'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          pr-mode: false
